todo_list/urls.py
import debug_toolbar
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from todo_list import settings
from todolist.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todolist/", include("todolist.urls")),
    path("", index, name="index"),
    path("__debug__/", include(debug_toolbar.urls)),
    path("accounts/", include("django.contrib.auth.urls")),
    path("favicon.ico", RedirectView.as_view(url="/static/favicon.ico")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todolist/urls.py
from django.urls import path

from todolist.views import (
    TaskListView,
    TagListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskToggleStatusView, UserCreateView,
)

urlpatterns = [
    path(
        "tasks/",
        TaskListView.as_view(),
        name="task-list"
    ),
    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "tasks/update/<int:pk>/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/toggle_status/<int:pk>/",
        TaskToggleStatusView.as_view(),
        name="task-toggle-status"
    ),
    path(
        "tasks/delete/<int:pk>/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tags/",
        TagListView.as_view(),
        name="tag-list"
    ),
    path(
        "tags/create/",
        TagCreateView.as_view(),
        name="tag-create"
    ),
    path(
        "tags/update/<int:pk>/",
        TagUpdateView.as_view(),
        name="tag-update"
    ),
    path(
        "tags/delete/<int:pk>/",
        TagDeleteView.as_view(),
        name="tag-delete"
    ),
    path(
        "user_create/",
        UserCreateView.as_view(),
        name="user-create"
    ),
]

app_name = "todolist"

todolist/models.py
from datetime import datetime

from django.contrib.auth.models import AbstractUser
from django.db import models

from todo_list import settings


class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    current_date = models.DateTimeField(default=datetime.now)
    status = models.BooleanField(default=False)
    tags = models.ManyToManyField(
        "Tag",
        related_name="tasks",
        blank=True
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="tasks",
        on_delete=models.CASCADE,
    )

    class Meta:
        ordering = [
            "status",
            "-created_at",
        ]

    def __str__(self):
        return f"{self.title}"


class Tag(models.Model):
    name = models.CharField(max_length=100)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="tags",
        on_delete=models.CASCADE,
    )

    class Meta:
        ordering = [
            "name"
        ]
        constraints = [
            models.UniqueConstraint(
                fields=["name", "user"],
                name="unique_tag_name_for_user",
            )
        ]

    def __str__(self):
        return f"{self.name}"


class User(AbstractUser):
    pass

todolist/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from todolist.models import (
    Task,
    Tag,
    User,
)


class TaskCreateUpdateForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.prefetch_related("tasks"),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    deadline = forms.DateTimeField(
        widget=forms.DateTimeInput,
        required=False,
    )

    class Meta:
        model = Task
        fields = [
            "title",
            "description",
            "deadline",
            "tags",
        ]


class TaskSearchForm(forms.Form):
    title = forms.CharField(
        label="",
        required=False,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by task title",
            }
        )
    )


class TagCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = [
            "name",
        ]


class TagSearchForm(forms.Form):
    name = forms.CharField(
        label="",
        required=False,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by tag name",
            }
        )
    )


class UserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "password1",
            "password2",
        ]

todolist/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from todolist.forms import (
    TaskCreateUpdateForm,
    TagCreateUpdateForm,
    UserCreateForm, TaskSearchForm, TagSearchForm,
)
from todolist.models import Task, Tag


def index(request: HttpRequest) -> HttpResponse:
    if not request.user.is_authenticated:
        return render(
            request,
            "todolist/index.html",
            {
                "number_of_tasks": 0,
                "number_of_tags": 0,
                "number_of_visits": 0}
        )

    user = request.user
    number_of_user_tasks = Task.objects.filter(user=user).count()
    number_of_user_tags = Tag.objects.filter(user=user).count()

    number_of_tasks = number_of_user_tasks
    number_of_tags = number_of_user_tags

    number_of_visits = request.session.get("number_of_visits", 1)
    request.session["number_of_visits"] = number_of_visits + 1

    context = {
        "number_of_tasks": number_of_tasks,
        "number_of_tags": number_of_tags,
        "number_of_visits": number_of_visits,
    }

    return render(
        request,
        "todolist/index.html",
        context=context,
    )


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    context_object_name = "tasks"
    template_name = "todolist/task_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)
        title = self.request.GET.get("title")
        context["search_form"] = TaskSearchForm(
            initial={"title": title}
        )

        return context

    def get_queryset(self):
        queryset = Task.objects.filter(user=self.request.user)
        form = TaskSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                title__icontains=form.cleaned_data["title"],
            )

        return queryset


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    form_class = TaskCreateUpdateForm
    context_object_name = "task"
    template_name = "todolist/task_create_update.html"
    success_url = reverse_lazy("todolist:task-list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskCreateUpdateForm
    context_object_name = "task"
    template_name = "todolist/task_create_update.html"
    success_url = reverse_lazy("todolist:task-list")

    def form_valid(self, form):
        task = form.save(commit=False)
        task.save()
        form.instance.tags.set(form.cleaned_data["tags"])

        return super().form_valid(form)


class TaskToggleStatusView(LoginRequiredMixin, generic.View):
    def post(self, request, pk):
        task = Task.objects.get(pk=pk, user=self.request.user)
        task.status = not task.status
        task.save()

        return redirect("todolist:task-list")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    context_object_name = "task"
    template_name = "todolist/task_delete.html"
    success_url = reverse_lazy("todolist:task-list")


class TagListView(LoginRequiredMixin, generic.ListView):
    model = Tag
    context_object_name = "tags"
    template_name = "todolist/tag_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TagListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name")
        context["search_form"] = TagSearchForm(
            initial={"name": name}
        )

        return context

    def get_queryset(self):
        queryset = Tag.objects.filter(user=self.request.user)
        form = TagSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])

        return queryset


class TagCreateView(LoginRequiredMixin, generic.CreateView):
    form_class = TagCreateUpdateForm
    context_object_name = "tag"
    template_name = "todolist/tag_create_update.html"
    success_url = reverse_lazy("todolist:tag-list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TagUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Tag
    form_class = TagCreateUpdateForm
    context_object_name = "tag"
    template_name = "todolist/tag_create_update.html"
    success_url = reverse_lazy("todolist:tag-list")


class TagDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Tag
    context_object_name = "tag"
    template_name = "todolist/tag_delete.html"
    success_url = reverse_lazy("todolist:tag-list")


class UserCreateView(generic.CreateView):
    form_class = UserCreateForm
    context_object_name = "user"
    template_name = "todolist/user_create.html"
    success_url = reverse_lazy("login")

templates/todolist/index.html
{% extends "base.html" %}
{% block content %}
  <div
      id="page-content"
      class="page
             container-fluid
             vh-100
             d-flex
             flex-column
             justify-content-between
             text-white"
  >
    {% if user.is_authenticated %}
      <div class="d-flex flex-column justify-content-center align-items-center flex-grow-1 text-center">
        <h1 class="fade-in">Your TODO List consists the following content:</h1>
        <hr>
        <ol class="inline-list mb-4 fade-in">
          <li>Number of your tasks: {{ number_of_tasks }}</li>
          <li>Number of your tags: {{ number_of_tags }}</li>
        </ol>
      </div>
    {% else %}
      <div class="d-flex flex-column justify-content-center align-items-center flex-grow-1 text-center">
        <h1 class="mb-4 fade-in">Welcome to the TODO List Service</h1>
        <h3 class="fade-in">Join us to manage your tasks</h3>
      </div>
    {% endif %}

    <div class="text-center pb-3">
      <hr>
      <p>Your visits: {{ number_of_visits }} time{{ number_of_visits|pluralize }}</p>
    </div>
  </div>
{% endblock %}

templates/todolist/tag_create_update.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <div id="page-content" class="page container-fluid text-white">
    <h1>
      {{ object|yesno:"Update,Create" }} a Tag
    </h1>
    <form action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <input
          type="submit"
          value="{{ object|yesno:'Update,Create' }}"
          class="btn btn-primary"
      >
    </form>
  </div>
{% endblock %}

templates/todolist/tag_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <div id="page-content" class="page container-fluid">
    <h1>Deleting Tag</h1>
    <p>You're going to delete a tag: <strong>{{ tag.name }}</strong></p>
    <p>
      <i>
        If you're really sure to delete a tag, press a <strong>"Delete"</strong> button bellow.
      </i>
    </p>
    <form action="" method="post">
      {% csrf_token %}
      <input
          type="submit"
          value="Delete"
          class="btn btn-danger"
      >
    </form>
  </div>
{% endblock %}

templates/todolist/tag_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <div id="page-content" class="page container-fluid">
    <div class="d-flex justify-content-center align-items-center position-relative my-3 py-3">
      <h1 class="text-white position-absolute" style="left: 50%; transform: translateX(-50%);">Tags List</h1>
      <a
          href="{% url 'todolist:tag-create' %}"
          class="btn btn-primary position-absolute"
          style="right: 0;"
      >
        Add Tag
      </a>
    </div>
    <div class="mt-4">
      <form action="" method="get" class="text-white">
      {% csrf_token %}
      {{ search_form|crispy }}
      <input
          type="submit"
          value="Search"
          class="btn btn-info"
      >
    </form>
    </div>
    <hr class="text-white-50">
    {% if not user.tags.all %}
      <p class="text-white">There are no created tags!</p>
    {% else %}
      <table class="table table-bordered bg-white">
        <thead>
          <tr>
            <th class="text-center">
              Name
            </th>
            <th class="text-center">
              Update
            </th>
            <th class="text-center">
              Delete
            </th>
          </tr>
        </thead>
        <tbody>
          {% for tag in page_obj %}
            <tr>
              <td class="d-flex justify-content-center align-items-center">
                {{ tag.name }}
              </td>
              <td class="text-center">
                <a
                    href="{% url 'todolist:tag-update' pk=tag.id %}"
                    class="btn btn-info d-inline-block"
                >
                  Update
                </a>
              </td>
              <td class="text-center">
                <a
                    href="{% url 'todolist:tag-delete' pk=tag.id %}"
                    class="btn btn-danger d-inline-block"
                >
                  Delete
                </a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% endif %}
  </div>
{% endblock %}

templates/todolist/task_create_update.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <div id="page-content" class="page container-fluid text-white mt-4 mb-4">
    <h1 class="text-center">{{ object|yesno:"Update,Create" }} a Task</h1>
    <hr>
    <form action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <input
          type="submit"
          value="{{ object|yesno:'Update,Create' }}"
          class="btn btn-primary"
      >
    </form>
  </div>
{% endblock %}

templates/todolist/task_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <div id="page-content" class="page container-fluid">
    <h1>Task Deletion</h1>
    <p>You're going to delete the task:
      <strong>{{ task.title }}</strong>
    </p>
    <p>
      <i>
        If you're really sure to delete this task, press <strong>"Delete"</strong> button below.
      </i>
    </p>
    <form action="" method="post">
      {% csrf_token %}
      <input
          type="submit"
          value="Delete"
          class="btn btn-danger"
      >
    </form>
  </div>
{% endblock %}

templates/todolist/task_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <div
      id="page-content"
      class="page
             container-fluid
             my-2
             py-3
             scroll-smooth"
  >
    <div
        class="d-flex
               justify-content-center
               align-items-center
               w-100
               position-relative
               my-2
               py-3"
    >
      <h1
          class="text-white position-absolute my-4 py-4"
          style="left: 50%; transform: translateX(-50%);"
      >
        Your Tasks List
      </h1>
      <a
          href="{% url 'todolist:task-create' %}"
          class="btn btn-primary position-absolute my-4"
          style="right: 0;"
      >
        Add Task
      </a>
    </div>
    <form action="" method="get" class="text-white mt-4">
      {{ search_form|crispy }}
      <input
          type="submit"
          value="Search"
          class="btn btn-info text-white"
      >
    </form>
    <hr class="text-white-50">
    {% if not user.tasks.all %}
      <p class="text-white">There are no created tasks!</p>
    {% else %}
      <ol class="list-group task-list">
        {% for task in tasks %}
          <li class="list-group-item">
            <div class="d-flex justify-content-between align-items-center">
              <h5>
                <strong>{{ task.title }}</strong>
                <span style="color: {{ task.status|yesno:'green;,red;' }}">
                  {{ task.status|yesno:"Done,Not Done" }}
                </span>
              </h5>
              <form
                  action="{% url 'todolist:task-toggle-status' pk=task.id %}"
                  method="post"
              >
                {% csrf_token %}
                <input
                    type="submit"
                    value="{{ task.status|yesno:'Undo,Complete' }}"
                    class="btn
                           {{ task.status|yesno:'btn-secondary,btn-success' }}
                           mx-2"
                >
              </form>
            </div>
            <p>
              <strong>
                Task ID:
              </strong>
              {{ task.id }}
            </p>
            <p>
              <strong>Description:</strong>
              {{ task.description }}
            </p>
            <p>
              <strong>Created at:</strong>
              {{ task.created_at|date:"d.m.Y, H:m:s" }}
            </p>
            <p>
              {% if task.deadline %}
                <strong>Deadline:</strong>
                {{ task.deadline|date:"d.m.Y H:m:s" }}
                {% if not task.status %}
                  {% if task.deadline < task.current_date%}
                    <span class="bg-danger text-white px-2">Expired</span>
                  {% else %}
                    <span class="bg-info text-white px-2">In progress</span>
                  {% endif %}
                {% endif %}
              {% endif %}
            </p>
            <p>
              <strong>Tags:</strong>
              {% if task.tags.all %}
                {% for tag in task.tags.all %}
                  {{ tag.name }},
                {% endfor %}
              {% else %}
                <span>
                  Task has no tags.
                </span>
              {% endif %}
            </p>
            <hr>
            <div
                class="d-flex
                       justify-content-between
                       align-items-center
                       mx-2"
            >
              <a
                  href="{% url 'todolist:task-update' pk=task.id %}"
                  class="btn btn-info"
              >
                Update
              </a>
              <a
                  href="{% url 'todolist:task-delete' pk=task.id %}"
                  class="btn btn-danger"
              >
                Delete
              </a>
            </div>
          </li>
        {% endfor %}
      </ol>
    {% endif %}
  </div>
{% endblock %}

templates/todolist/user_create.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <div id="page-content"
       class="page
              d-flex
              flex-column
              min-vh-100
              justify-content-center
              align-items-center
              text-start
              w-100
              text-white"
  >
    <div class="col-12 col-sm-10 col-md-8 col-lg-8">
      <h1 class="mb-4 text-center">Create a new user of TODO List Service</h1>
      <form
          action="?page={% url 'login' %}"
          method="post"
      >
        {% csrf_token %}
        {{ form|crispy }}
        <input
            type="submit"
            value="Create"
            class="btn btn-success w-100"
        >
      </form>
    </div>
  </div>
{% endblock %}