todo_list/urls.py
import debug_toolbar
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from todo_list import settings
from todolist.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todolist/", include("todolist.urls")),
    path("", index, name="index"),
    path("__debug__/", include(debug_toolbar.urls)),
    path("accounts/", include("django.contrib.auth.urls")),
    path("favicon.ico", RedirectView.as_view(url="/static/favicon.ico")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todolist/urls.py
from django.urls import path

from todolist.views import (
    TaskListView,
    TagListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskToggleStatusView, UserCreateView,
)

urlpatterns = [
    path(
        "tasks/",
        TaskListView.as_view(),
        name="task-list"
    ),
    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "tasks/update/<int:pk>/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/toggle_status/<int:pk>/",
        TaskToggleStatusView.as_view(),
        name="task-toggle-status"
    ),
    path(
        "tasks/delete/<int:pk>/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tags/",
        TagListView.as_view(),
        name="tag-list"
    ),
    path(
        "tags/create/",
        TagCreateView.as_view(),
        name="tag-create"
    ),
    path(
        "tags/update/<int:pk>/",
        TagUpdateView.as_view(),
        name="tag-update"
    ),
    path(
        "tags/delete/<int:pk>/",
        TagDeleteView.as_view(),
        name="tag-delete"
    ),
    path(
        "user_create/",
        UserCreateView.as_view(),
        name="user-create"
    ),
]

app_name = "todolist"

templates/includes/pagination.html
{% load query_transform %}
<ul class="pagination justify-content-center">
  {% if page_obj.has_previous %}
    <li class="page-item">
      <a
          href="?page={{ page_obj.previous_page_number }}"
          class="page-link"
      >
        Prev
      </a>
    </li>
  {% endif %}

  <li class="page-item active">
    <span class="page-link">
      {{ page_obj.number }} / {{ paginator.num_pages }}
    </span>
  </li>

  {% if page_obj.has_next %}
    <li class="page-item">
      <a
          href="?page={{ page_obj.next_page_number }}"
          class="page-link"
      >
        Next
      </a>
    </li>
  {% endif %}
</ul>

templates/includes/sidebar.html
<div class="d-flex vh-100">
  <!-- Sidebar -->
  <div id="sidebar" class="sidebar d-flex flex-column align-items-center justify-content-center px-2">
    <ul class="list-group w-100">
      {% if user.is_authenticated %}
        <div class="mx-4 text-center">
          <h5 class="text-white">Hello, <strong>{{ user.username }}</strong>!</h5>
          <hr>
          <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Logout" class="btn btn-danger w-100 mb-4">
          </form>
        </div>
      {% else %}
        <div class="mb-4 text-center">
          <h5 class="text-white">Hello, <strong>Visitor</strong>!</h5>
          <hr>
          <div class="d-flex justify-content-center">
            <a href="{% url 'login' %}" class="btn btn-primary mx-1">Login</a>
            <a href="{% url 'todolist:user-create' %}" class="btn btn-success">Sign Up</a>
          </div>
        </div>
      {% endif %}
      <li class="list-group-item text-center">
        <a href="{% url 'index' %}" class="text-decoration-none">Home</a>
      </li>
      <li class="list-group-item text-center">
        <a href="{% url 'todolist:task-list' %}" class="text-decoration-none">Tasks</a>
      </li>
      <li class="list-group-item text-center">
        <a href="{% url 'todolist:tag-list' %}" class="text-decoration-none">Tags</a>
      </li>
    </ul>
  </div>
</div>